### ISSUE TITLE
Cannot run `git submodule update` using a non-root user in Linux

### ISSUE THREAD

**Issue by WuyangFF95** [lrgr/tcsm#3]
Dear @wir963 ,

I've created a conda environment as the direction, and named it as **"tcsm"**. But I cannot run the last step of sub-module installation:
`git submodule update`

The error is printed as follows:

> (base) [wuyang@monster tcsm]$ conda activate tcsm
> (tcsm) [wuyang@monster tcsm]$ git submodule init
> (tcsm) [wuyang@monster tcsm]$ git submodule update
> Cloning into 'mutation-signatures-viz'...
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> Clone of 'git@github.com:lrgr/mutation-signatures-viz.git' into submodule path 'mutation-signatures-viz' failed

Can you help me to fix this issue? Thanks!

**Comment by wir963** [comment]
Hey @WuyangFF95 ,

Sorry that you ran into that issue. The issue seems to be related to use https://github.com/lrgr/mutation-signatures-viz as a submodule but I'm not sure why you are getting a permission denied. One possibility is that we are using the ssh url (in the .gitmodules file) instead of the https url, which might cause an issue is you don't have an ssh key associated with you github account.

When you cloned the original repository did you use ssh or https? Do you have a ssh key associated with your github account?

Thanks, Welles

**Comment by WuyangFF95** [comment]
Hi @wir963 ,

Indeed, I don't have a SSH key. So what should I do next?

**Comment by wir963** [comment]
Hey @WuyangFF95 ,

As a general recommendation, I would suggest that you generate an ssh key and save it to your github account, which you can do using these directions - https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

However, I don't think it's best practice to assume that someone will have ssh set-up so I updated the `.gitmodules` file to use https instead of ssh. Given that you already did `git submodule init`, I think it might be easiest to just delete your local `tcsm` directory and clone it again.

Best, Welles

**Comment by wir963** [comment]
@WuyangFF95 did that fix your problem?

**Comment by WuyangFF95** [comment]
It works! Thank you Welles!
